Add Node Resolution advanced topic
AllStarLink/ASL3-Manual pull request #20
Opened 2024-08-10 19:05 UTC by KB4MDD

This adds a Node Resolution topic to the advanced section.

2024-08-10 19:25 UTC, Allan-N requested changes

2024-08-10 19:25 UTC, Allan-N commented on docs/adv-topics/noderesolution.md
> +app_rpt has three ways to resolve a node number to an IP address.
Add a blank line after this sentence to separate the text from the list.

2024-08-10 19:25 UTC, Allan-N commented on docs/adv-topics/noderesolution.md
> +*Note:  The AllStarLink network maintains security by requiring node owners to register with AllStarLink. Before a node is published to our directory, it must successfully authenticate and register w
... to our directory it must ...

2024-08-10 19:25 UTC, Allan-N commented on docs/adv-topics/noderesolution.md
> +app_rpt can use an external node directory file to perform node resolution.  The ASL3-Update-NodeList package is used to periodically download the current list of authenticated nodes.
ASL3-Update-NodeList package --> asl3-update-nodeList service

2024-08-10 19:25 UTC, Allan-N commented on docs/adv-topics/noderesolution.md
> +When using DNS app_rpt must know the length of the longest node number.  The current maximum is 6 digits.  This number can be overriden in rpt.conf by adding the **max_dns_node_length** key and value
overriden --> overridden

2024-08-10 19:25 UTC, Allan-N commented on docs/adv-topics/noderesolution.md
> +To configure a static node, enter the information for te node in rpt.conf under the **[node]** stanza.  Here is an example configuration:
for te node --> for the node

2024-08-10 19:29 UTC, Allan-N requested changes
You also want to update .../ASL3-Manual/mkdocs.yml

2024-08-11 00:29 UTC, Allan-N requested changes

2024-08-11 00:29 UTC, Allan-N commented on docs/adv-topics/noderesolution.md
> +app_rpt has three ways to resolve a node number to an IP address.
I apologize for not making my comment clear.  I was asking for a blank line between the "app_rpt has three ways ..." and the first "* An external node ...".  Without the break the list does not show up as a list.

2024-08-11 00:34 UTC, Allan-N requested changes

2024-08-11 00:34 UTC, Allan-N commented on docs/adv-topics/noderesolution.md
> +*Note:  The AllStarLink network maintains security by requiring node owners to register with AllStarLink. Beforehttps://github.com/AllStarLink/asl3-update-nodelist) a node is published to our directo
It looks like a URL found it's way into the text :-(

2024-08-11 16:58 UTC, tsawyer approved these changes
Generally looks good. But did not proof read.

2024-08-12 12:39 UTC, Allan-N approved these changes
Looks great!

2024-08-12 15:37 UTC, merged