autopatch updates with IAX/SIP notes
AllStarLink/ASL3-Manual pull request #97
Opened 2024-12-24 15:18 UTC by knobby4444

Major step up in autopatch documentation.  Added Mason's github info on voip.ms IAX setup and my own flowroute SIP setup info.  Other updates include duplex info.

2024-12-24 18:11 UTC, jxmx approved these changes

2024-12-25 01:08 UTC, Allan-N requested changes
General things to look at :
- Sometimes you refer to the file (rpt.conf) and other times the full path (/etc/asterisk/rpt.conf).
- I noticed that sometimes you refer to "IAX and PJSIP" and other times "PJSIP and IAX".
- It would be good to use a spell checker on the entire file

2024-12-25 01:08 UTC, Allan-N commented on docs/adv-topics/autopatch.md
> +### extentions.conf
extentions.conf --> extensions.conf

... and do you want to use the full path?

2024-12-25 01:08 UTC, Allan-N commented on docs/adv-topics/autopatch.md
> +For outbound IAX connections extensions.conf:
For outbound IAX connections, add :

2024-12-25 01:08 UTC, Allan-N commented on docs/adv-topics/autopatch.md
> +For outbound SIP connections extensions.conf, this example uses IP auth:
For outbound SIP connections using IP auth, add :

2024-12-25 01:08 UTC, Allan-N commented on docs/adv-topics/autopatch.md
> +Setup 911 extention
To setup the 911 extension, add :

(and yes, here you also need to correct the spelling of extension :-)

2024-12-28 14:13 UTC, knobby4444 commented
Happy to update the misspellings.  If you are looking for someone to do things like update every instance of a filename and add or remove the full path, I'm not the right person for that type of editing.

2024-12-28 15:14 UTC, jxmx commented
We should always be using full paths to files. They should be updated/fixed by the requestor at merge time.

2025-01-02 10:33 UTC, knobby4444 commented
It feels to me that with the amount of documentation updates that are needed just to get to a point where people can be successful by using the documentation, perhaps a new wiki or something that's easier to update would better serve the project.

2025-01-02 18:19 UTC, jxmx commented
@knobby4444 The great thing about documentation platforms is no one reads it regardless of how you publish it...

2025-01-07 21:55 UTC, Allan-N approved these changes

2025-01-11 14:37 UTC, merged